# Generated by Django 5.2.17 on 2026-09-24 04:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('QUIZ', 'Module quiz'), ('FINAL', 'Final assessment')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_attempts', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='training.module')),
                ('training_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='training.trainingversion')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score_points', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_points', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pass_percentage_snapshot', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='training.trainingassignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presented_position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('points_possible', models.DecimalField(decimal_places=2, max_digits=8)),
                ('points_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='assessments.assessmentquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessments.assessmentattempt')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='assessments.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('TRUE_FALSE', 'True or false')], default='SINGLE_CHOICE', max_length=13)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FROZEN', 'Frozen')], default='DRAFT', max_length=6)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_revisions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assessments.question')),
            ],
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='assessments.questionrevision'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='question_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='assessments.questionrevision'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='question_revisions',
            field=models.ManyToManyField(related_name='assessments', through='assessments.AssessmentQuestion', to='assessments.questionrevision'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['assignment', 'assessment', 'status'], name='attempt_assignment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('assignment', 'assessment', 'attempt_number'), name='unique_assessment_attempt_no'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1), ('maximum_points__gt', 0)), name='attempt_positive_values'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score_points__isnull', True), models.Q(('score_points__gte', 0), ('score_points__lte', models.F('maximum_points'))), _connector='OR'), name='attempt_score_range'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('pass_percentage_snapshot__gte', 0), ('pass_percentage_snapshot__lte', 100)), name='attempt_pass_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__isnull', True), ('deadline_at__gte', models.F('started_at')), _connector='OR'), name='attempt_deadline_order'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('submitted_at__isnull', True), ('submitted_at__gte', models.F('started_at')), _connector='OR'), name='attempt_submission_order'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('passed__isnull', True), ('score_points__isnull', True), ('status', 'IN_PROGRESS'), ('submitted_at__isnull', True)), models.Q(('passed__isnull', False), ('score_points__isnull', False), ('status__in', ['SUBMITTED', 'EXPIRED']), ('submitted_at__isnull', False)), models.Q(('passed__isnull', True), ('score_points__isnull', True), ('status', 'ABANDONED'), ('submitted_at__isnull', False)), _connector='OR'), name='attempt_result_fields'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'is_active'], name='question_topic_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'assessment_question'), name='unique_attempt_question_answer'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'presented_position'), name='unique_attempt_answer_position'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.CheckConstraint(condition=models.Q(('points_possible__gt', 0), ('presented_position__gte', 1)), name='answer_positive_values'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.CheckConstraint(condition=models.Q(('points_awarded__isnull', True), models.Q(('points_awarded__gte', 0), ('points_awarded__lte', models.F('points_possible'))), _connector='OR'), name='answer_awarded_range'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answered_at__isnull', True), ('selected_option__isnull', True)), models.Q(('answered_at__isnull', False), ('selected_option__isnull', False)), _connector='OR'), name='answer_response_fields'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_correct__isnull', True), ('points_awarded__isnull', True)), models.Q(('is_correct__isnull', False), ('points_awarded__isnull', False)), _connector='OR'), name='answer_grade_fields'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.UniqueConstraint(fields=('question', 'revision_number'), name='unique_question_revision'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='question_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frozen_at__isnull', True), ('status', 'DRAFT')), models.Q(('frozen_at__isnull', False), ('status', 'FROZEN')), _connector='OR'), name='question_revision_freeze_date'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question_revision', 'position'), name='unique_question_option_order'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='question_option_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'position'), name='unique_assessment_question_pos'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'question_revision'), name='unique_assessment_question_rev'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', 0), ('position__gte', 1)), name='assessment_question_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('training_version', 'kind', 'sequence'), name='unique_version_assessment_seq'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_required', True), ('kind', 'FINAL'), ('module__isnull', True), ('sequence', 1)), models.Q(('kind', 'QUIZ'), ('module__isnull', False)), _connector='OR'), name='assessment_kind_scope'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1), ('sequence__gte', 1)), name='assessment_positive_limits'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('pass_percentage__gte', 0), ('pass_percentage__lte', 100)), name='assessment_pass_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_minutes__isnull', True), ('time_limit_minutes__gte', 1), _connector='OR'), name='assessment_time_limit_positive'),
        ),
    ]
