# Generated by Django 5.2.17 on 2026-09-24 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_label_snapshot', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(help_text='Django app_label.model_name', max_length=100)),
                ('entity_id', models.CharField(max_length=64)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'occurred_at'], name='audit_entity_time_idx'), models.Index(fields=['actor', 'occurred_at'], name='audit_actor_time_idx'), models.Index(fields=['action', 'occurred_at'], name='audit_action_time_idx')],
            },
        ),
    ]
