# Generated by Django 5.2.17 on 2026-09-24 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee_code_snapshot', models.CharField(max_length=30)),
                ('employee_name_snapshot', models.CharField(max_length=150)),
                ('training_title_snapshot', models.CharField(max_length=200)),
                ('version_number_snapshot', models.PositiveIntegerField()),
                ('document_file', models.FileField(blank=True, max_length=255, upload_to='certificates/%Y/%m/')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='training.trainingassignment')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('qualifying_final_attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='assessments.assessmentattempt')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
                ('training_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='training.trainingversion')),
            ],
            options={
                'indexes': [models.Index(fields=['training_version', 'issued_at'], name='certificate_version_issued_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('version_number_snapshot__gte', 1)), name='certificate_version_positive'), models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('issued_at')), _connector='OR'), name='certificate_revocation_order'), models.CheckConstraint(condition=models.Q(models.Q(('revocation_reason', ''), ('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('revoked_at__isnull', False), models.Q(('revocation_reason', ''), _negated=True)), _connector='OR'), name='certificate_revocation_fields')],
            },
        ),
    ]
