# Generated by Django 5.2.17 on 2026-09-24 04:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('TEXT', 'Written lesson')], max_length=5)),
                ('body', models.TextField(blank=True)),
                ('video_file', models.FileField(blank=True, max_length=255, upload_to='training/videos/%Y/%m/')),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('video_checksum', models.CharField(blank=True, max_length=64)),
                ('is_required', models.BooleanField(default=True)),
                ('minimum_watch_percent', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='training.module')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RoleTrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('due_in_days', models.PositiveIntegerField(default=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_role_requirements', to=settings.AUTH_USER_MODEL)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_requirements', to='organization.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('catalog_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=12)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('ROLE', 'Job role')], default='MANUAL', max_length=6)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_trainings', to=settings.AUTH_USER_MODEL)),
                ('department_at_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_assignments', to='organization.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_assignments', to='organization.employee')),
                ('job_role_at_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_assignments', to='organization.jobrole')),
                ('role_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='training.roletrainingrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_position_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('watched_ranges', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_progress', to='training.lesson')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_progress', to='training.trainingassignment')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_training_versions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_training_versions', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='training.training')),
            ],
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='training_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='training.trainingversion'),
        ),
        migrations.AddField(
            model_name='roletrainingrequirement',
            name='training_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_requirements', to='training.trainingversion'),
        ),
        migrations.AddField(
            model_name='module',
            name='training_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='training.trainingversion'),
        ),
        migrations.CreateModel(
            name='VideoWatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('starting_position_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ending_position_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('active_watch_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_normally', models.BooleanField(default=False)),
                ('session_identifier', models.CharField(blank=True, max_length=128)),
                ('device_identifier', models.CharField(blank=True, max_length=128)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_watch_sessions', to='training.trainingassignment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watch_sessions', to='training.lesson')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'position'), name='unique_lesson_position'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='lesson_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_watch_percent__gte', 0), ('minimum_watch_percent__lte', 100)), name='lesson_watch_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_type', 'TEXT'), ('video_checksum', ''), ('video_duration_seconds__isnull', True), ('video_file', ''), models.Q(('body', ''), _negated=True)), models.Q(('content_type', 'VIDEO'), ('video_duration_seconds__gt', 0), ('video_duration_seconds__isnull', False), models.Q(('video_file', ''), _negated=True), models.Q(('video_checksum', ''), _negated=True)), _connector='OR'), name='lesson_content_fields'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['assignment', 'completed_at'], name='progress_completion_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('assignment', 'lesson'), name='unique_assignment_lesson'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.CheckConstraint(condition=models.Q(('last_position_seconds__gte', 0)), name='progress_position_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.CheckConstraint(condition=models.Q(('last_accessed_at__gte', models.F('started_at'))), name='progress_access_order'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='progress_completion_order'),
        ),
        migrations.AddIndex(
            model_name='trainingversion',
            index=models.Index(fields=['training', 'status'], name='training_version_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingversion',
            constraint=models.UniqueConstraint(fields=('training', 'version_number'), name='unique_training_version'),
        ),
        migrations.AddConstraint(
            model_name='trainingversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='training_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='trainingversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('published_by__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('published_by__isnull', False), ('status__in', ['PUBLISHED', 'RETIRED'])), _connector='OR'), name='training_publication_fields'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['employee', 'status'], name='assignment_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['status', 'due_at'], name='assignment_due_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['training_version', 'status'], name='assignment_version_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingassignment',
            constraint=models.UniqueConstraint(fields=('employee', 'training_version'), name='unique_employee_version'),
        ),
        migrations.AddConstraint(
            model_name='trainingassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role_requirement__isnull', True), ('source', 'MANUAL')), models.Q(('role_requirement__isnull', False), ('source', 'ROLE')), _connector='OR'), name='assignment_source_fields'),
        ),
        migrations.AddConstraint(
            model_name='trainingassignment',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__isnull', True), ('due_at__gte', models.F('assigned_at')), _connector='OR'), name='assignment_due_order'),
        ),
        migrations.AddConstraint(
            model_name='trainingassignment',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('started_at__gte', models.F('assigned_at')), _connector='OR'), name='assignment_start_order'),
        ),
        migrations.AddConstraint(
            model_name='trainingassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('completed_at__isnull', False), ('started_at__isnull', False), ('status', 'COMPLETED')), models.Q(('cancelled_at__isnull', False), ('completed_at__isnull', True), ('status', 'CANCELLED')), models.Q(('cancelled_at__isnull', True), ('completed_at__isnull', True), ('status__in', ['ASSIGNED', 'IN_PROGRESS'])), _connector='OR'), name='assignment_status_dates'),
        ),
        migrations.AddConstraint(
            model_name='trainingassignment',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='assignment_completion_order'),
        ),
        migrations.AddConstraint(
            model_name='trainingassignment',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_at__isnull', True), ('cancelled_at__gte', models.F('assigned_at')), _connector='OR'), name='assignment_cancel_order'),
        ),
        migrations.AddIndex(
            model_name='roletrainingrequirement',
            index=models.Index(fields=['job_role', 'is_active'], name='role_requirement_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='roletrainingrequirement',
            constraint=models.UniqueConstraint(fields=('job_role', 'training_version'), name='unique_role_training_version'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('training_version', 'position'), name='unique_module_position'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='module_position_positive'),
        ),
        migrations.AddIndex(
            model_name='videowatchsession',
            index=models.Index(fields=['assignment', 'lesson', 'started_at'], name='watch_session_history_idx'),
        ),
        migrations.AddIndex(
            model_name='videowatchsession',
            index=models.Index(fields=['session_identifier'], name='watch_session_identifier_idx'),
        ),
        migrations.AddConstraint(
            model_name='videowatchsession',
            constraint=models.CheckConstraint(condition=models.Q(('active_watch_seconds__gte', 0), ('starting_position_seconds__gte', 0)), name='watch_session_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='videowatchsession',
            constraint=models.CheckConstraint(condition=models.Q(('ending_position_seconds__isnull', True), ('ending_position_seconds__gte', 0), _connector='OR'), name='watch_session_end_position'),
        ),
        migrations.AddConstraint(
            model_name='videowatchsession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='watch_session_time_order'),
        ),
        migrations.AddConstraint(
            model_name='videowatchsession',
            constraint=models.CheckConstraint(condition=models.Q(('completed_normally', False), ('ended_at__isnull', False), _connector='OR'), name='watch_session_normal_end'),
        ),
        migrations.AddConstraint(
            model_name='videowatchsession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ending_position_seconds__isnull', False), _connector='OR'), name='watch_session_end_required'),
        ),
    ]
